name: Update README ‚≠ê
on: [push, workflow_dispatch]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1641438
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2025
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update README stars
